### ISSUE TITLE
[BUG]  small Ogg files gets uploaded as voice note instead of as audio / document 

### ISSUE THREAD

**Issue by SpEcHiDe** [EDM115/unzip-bot#164]
**Describe the bug**

Create an archive containing less than 10mb OGG file

**To Reproduce**
1. Send the archive to the bot
2. Click on Normal button
3. Wait for the ogg file to get uploaded

**Screenshots**

![Screenshot_20230514-090345](https://github.com/EDM115/unzip-bot/assets/6317196/185edc2f-f038-45d9-8c98-7d0a0306fc1b)

**Comment by EDM115** [comment]
Nice to see someone else using TgX 🥰  
  
Regarding to the bug, I don't really have any solution.  
The code uses the `send_audio()` method from Pyrogram, and OGG files are recognized  
https://github.com/EDM115/unzip-bot/blob/7b9f211200bc8061fbe83f522e25876323edce76/unzipper/modules/ext_script/up_helper.py#L52
  
The fact that it happens for files < 10 Mb kind of reminds me that in the end the Telegram API can upload it not like you wanted (i.e. for Videos < 10 Mb, the thumbnail will be auto-generated if not provided)  
So I guess it's a Telegram's API problem  
  
Tho i keep the issue open if I can resolve it one day (I'm going to start working on the bot again 🥺)

**Comment by EDM115** [comment]
starting in 29a5ca0a77764dbf73b17c790461af6cf444ff30 and 60e83a2f5f5c3fbf936deb190b228d89e7bb9930, I'm forcing the use of some arguments that aren't available in `send_voice()`, only `send_audio()`  
there's a slight chance that this may force pyrogram to upload it as an audio, although if it still uploads as a voice message, then it's definitely telegram's fault

**Comment by SpEcHiDe** [comment]
I believe you can use a [Pyrogram fork](https://github.com/KurimuzonAkuma/pyrogram/pull/23) to temporarily fix the real issue.

**Comment by EDM115** [comment]
@SpEcHiDe I am already planning to switch to hydrogram anytime soon #258  
rn I'm just waiting for the ask() method to get fully implemented  
they may fix that, idk
