### ISSUE TITLE
[BUG] Impossible to connect for new users because it can't connect to logs channel 

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#326]
this started to happen since a few weeks, new people deploying the bot faced it and only a public group/channel could work.  
I wasn't concerned by this until I restarted a test bot for checking new features, and it failed (see attached logs). bot present in group since a year and interacting with it thousand times. not happening to the main bot but that's getting weird every moment

```logs
2024-07-29 12:00:56,490 - INFO - unzipper - MainThread - 854158484 : Restarting…
2024-07-29 12:00:58,684 - INFO - unzipper - MainThread - Starting bot…
2024-07-29 12:00:59,290 - WARNING - pyrogram.client - MainThread - [UnzipperBot] No plugin loaded from "modules"
2024-07-29 12:00:59,292 - ERROR - unzipper
- MainThread - Error in main loop: Telegram says: [400 PEER_ID_INVALID] - The peer id
being used is invalid or not known yet. Make sure you meet the peer before interacting with it
2024-07-29 12:00:59,292 - INFO - unzipper - MainThread - ℹ️ The bot goes sleeping at `2024/07/29 - 12:00:59` 😴
2024-07-29 12:00:59,292 - INFO - unzipper - MainThread - Bot stopped 😪
2024-07-29 12:00:59,293 - ERROR - unzipper
- MainThread - Error sending shutdown message: Telegram says: [400 PEER_ID_INVALID] -
The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```

**Comment by Disk6969** [comment]
id must be integer in pyrogram if you want the library to force cache the chat for the first time when a session didn't exist before and peer wasn't cached. 

if you want to keep the username support, just convert ids to int not username, so something like this should do

```py
LOGS_CHANNEL = os.environ.get("LOGS_CHANNEL")

if LOGS_CHANNEL.strip('-').isdigit():
    LOGS_CHANNEL = int(LOGS_CHANNEL)
```

also note that pyrogram is outdated, you may also face issues if a channel id was larger than 32 bit, for recently created channels, you can [apply a patch](https://t.me/pyrogramchat/618119) for that, but it is unrelated to yours if you face it for older channels

**Comment by EDM115** [comment]
@Disk6969 thanks for the help ❤️❤️  
a check like this will be done, also I plan to switch library anytime soon, see #258  
rn in holiday but will make a hotfix tomorrow, probably following your code advice :)
