### ISSUE TITLE
[BUG]  about heroku

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [EDM115/unzip-bot#337]
I have a question i want to deploy on heroku but my fear is heroku will ban my account like most of time i got with public codes and 2nd fear is sometimes bots working on vps as it is but when deploy on heroku its giving error so

**Comment by EDM115** [comment]
well thanks for the question  
I use the code myself on heroku for 3+ years without any issue, and even recently people have been deploying it successfully  
it is also mainly developed for Heroku, although I'm not making it more accessible to run on VPS as I will leave heroku. it will still be supported tho :)

**Comment by Ashrafmdmatin41** [comment]
ok bruh
