### ISSUE TITLE
A mini stats command for users too 

### ISSUE THREAD

**Issue by pr13260** [EDM115/unzip-bot#34]
this will make people see space left and some more things 

possibly less abuse if someone wanna run on their own server
A sample details/stats is provided
---✿ BOT STATS ✿---
Total Disk Space: 83.18 GiB 
Used Space: 53.35 GiB(64.2%) 
Free Space: 29.81 GiB 
CPU Usage: 0.2% 
RAM Usage: 12.9%
---Bot by *****---

**Comment by pr13260** [comment]
@EDM115 if you need it's codes ping me on tg or i will create a pr soon

**Comment by EDM115** [comment]
I will make it soon  
Private stats (like how many files processed by the bot for this user  
And what you asked for  
It already exists (but more detailed and for owner only)

**Comment by EDM115** [comment]
@pr13260 send `/stats` to the bot
Should be working

**Comment by pr13260** [comment]
done 
previously as owner only now it's better :D
