### ISSUE TITLE
Can not process passwords starting with /

### ISSUE THREAD

**Issue by reizhi** [EDM115/unzip-bot#36]
While the password is starting with /, the bot won't handle it.
`That archive is password protected 😡 Don't fool me !`

**Comment by EDM115** [comment]
Working on it… 👨‍💻

**Comment by EDM115** [comment]
@reizhi I just tested
It perfectly works
Just select "Extract a password protected archive 🔐"
It uses `pyromod.listen.ask()`, which process the answer as a string and not as a command

You get that error message because you used the Normal archive extract mode

**Comment by reizhi** [comment]
Thanks for your reply, I can confirm I've chosen password protected option because the log channel has got the password.
Please try to use this password `/BiPapa/()/()/RRR` then you can reproduce.

**Comment by EDM115** [comment]
![error](https://telegra.ph/file/cf00d9606e1943f9cba5e.jpg)  
  
The error come from p7zip, not from me

**Comment by reizhi** [comment]
We could use `-p"<password>"`, this method will work. 7z and p7z won't treat `"` as part of the password.
For those passwords with `"` inside, `\"` should be used instead. For example `-p"my\"password"` equals to `my"password`.

**Comment by EDM115** [comment]
I tried `7z x -p"/BiPapa/()/()/RRR"`, but we get the error as well 🙂

**Comment by EDM115** [comment]
As of today, I mark this bug as fixed  
![fixed bro](https://te.legra.ph/file/7f7b18458d38a2cbdebb7.jpg)  
  
Sorry for long delay @reizhi
