### ISSUE TITLE
error on some videos and some links 

### ISSUE THREAD

**Issue by kanjvt** [EDM115/unzip-bot#39]
-when i try to extract from direct link bot is not responded
-and upload as video mode instead file extracted as doc

**Comment by EDM115** [comment]
Can you attach any screenshots to complete your issue ?  
+ For the links, it works only with direct links, as example GDrive or Uptobox links doesn't work
+ And i will fix the error on video uploading in several days

**Comment by EDM115** [comment]
@kanjvt without further explanations from you in the 5 next days, I would be forced to close this issue
